DROP TABLE IF EXISTS EXCHANGE_RATES;

CREATE TABLE EXCHANGE_RATES (
			ID INT AUTO_INCREMENT PRIMARY KEY,
			C_FROM VARCHAR(5) NOT NULL,
			C_TO VARCHAR(5) NOT NULL,
			C_FACTOR DECIMAL ,
            C_DATE VARCHAR(20));
